name: tile38-php-client

services:
  tile38-113:
    image: tile38/tile38:1.13.0
  tile38-117:
    image: tile38/tile38:1.17.0
  tile38-122:
    image: tile38/tile38:1.22.0
  tile38-125:
    image: tile38/tile38:1.25.0
  tile38-130:
    image: tile38/tile38:1.30.0
  tile38-133:
    image: tile38/tile38:1.33.0
  tile38-138:
    image: tile38/tile38:1.38.0

  test:
    build: ./docker/php
    volumes:
      - .:/app
    working_dir: /app
    environment:
      TILE38_VERSIONS: "tile38-113:1.13.0 tile38-117:1.17.0 tile38-122:1.22.0 tile38-125:1.25.0 tile38-130:1.30.0 tile38-133:1.33.0 tile38-138:1.38.0"
    depends_on:
      - tile38-113
      - tile38-117
      - tile38-122
      - tile38-125
      - tile38-130
      - tile38-133
      - tile38-138
    command: ["sh", "-c", "composer install --no-interaction --prefer-dist && bash docker/scripts/run-integration.sh"]
